part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SIGNIN = _Paths.SIGNIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const SPLASH = _Paths.SPLASH;
  static const ON_BOARDING = _Paths.ON_BOARDING;
  static const FORGETPASSWORD = _Paths.FORGETPASSWORD;
  static const VERIFICATIONSCREEN = _Paths.VERIFICATIONSCREEN;
  static const NAVBAR = _Paths.NAVBAR;
  static const PROFILE = _Paths.PROFILE;
  static const BOOKINGS = _Paths.BOOKINGS;
  static const WISHLIST = _Paths.WISHLIST;
  static const CART = _Paths.CART;
  static const ACTIVITYDETAILS = _Paths.ACTIVITYDETAILS;
  static const GIFTPRVIEW = _Paths.GIFTPRVIEW;
  static const SENDGIFT = _Paths.SENDGIFT;
  static const CHOOSEPACKAGE = _Paths.CHOOSEPACKAGE;
  static const BOOKINGDETAIL = _Paths.BOOKINGDETAIL;
  static const CARDDETAILS = _Paths.CARDDETAILS;
  static const PAYMENTMETHODS = _Paths.PAYMENTMETHODS;
  static const BOOKINGCONFIRMATION = _Paths.BOOKINGCONFIRMATION;
  static const CATEGORIES_ACTIVITIES = _Paths.CATEGORIES_ACTIVITIES;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const SETTINGS = _Paths.SETTINGS;
  static const LANGUAGES = _Paths.LANGUAGES;
  static const NOTIFICATIOSETTINGS = _Paths.NOTIFICATIOSETTINGS;
  static const ADDNEWPAYMENT = _Paths.ADDNEWPAYMENT;
  static const SECURITYPAGE = _Paths.SECURITYPAGE;
  static const CHANGEPASSWORD = _Paths.CHANGEPASSWORD;
  static const OTPSCREEN = _Paths.OTPSCREEN;
  static const RESETPASSWORD = _Paths.RESETPASSWORD;
  static const DELETEACCOUNT = _Paths.DELETEACCOUNT;
  static const PERSONALINFORMATION = _Paths.PERSONALINFORMATION;
  static const PRIVACYPOLICY = _Paths.PRIVACYPOLICY;
  static const SUPPORTANDHELP = _Paths.SUPPORTANDHELP;
  static const BOOKINGDETAILS = _Paths.BOOKINGDETAILS;
  static const ENTERBOOKINGINFORMATION = _Paths.ENTERBOOKINGINFORMATION;
  static const CITIES_ACTVITIES = _Paths.CITIES_ACTVITIES;
  static const SEARCHPAGE = _Paths.SEARCHPAGE;
  static const CARTDETAILS = _Paths.CARTDETAILS;
  static const SPLASHSSS = _Paths.SPLASHSSS;
  static const EDITBOOKINGS = _Paths.EDITBOOKINGS;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SIGNIN = '/signin';
  static const SIGNUP = '/signup';
  static const SPLASH = '/splash';
  static const ON_BOARDING = '/on-boarding';
  static const FORGETPASSWORD = '/forgetpassword';
  static const VERIFICATIONSCREEN = '/verificationscreen';
  static const NAVBAR = '/navbar';
  static const PROFILE = '/profile';
  static const BOOKINGS = '/bookings';
  static const WISHLIST = '/wishlist';
  static const CART = '/cart';
  static const ACTIVITYDETAILS = '/activitydetails';
  static const GIFTPRVIEW = '/giftprview';
  static const SENDGIFT = '/sendgift';
  static const CHOOSEPACKAGE = '/choosepackage';
  static const BOOKINGDETAIL = '/bookingdetail';
  static const CARDDETAILS = '/carddetails';
  static const PAYMENTMETHODS = '/paymentmethods';
  static const BOOKINGCONFIRMATION = '/bookingconfirmation';
  static const CATEGORIES_ACTIVITIES = '/categories-activities';
  static const NOTIFICATIONS = '/notifications';
  static const SETTINGS = '/settings';
  static const LANGUAGES = '/languages';
  static const NOTIFICATIOSETTINGS = '/notificatiosettings';
  static const ADDNEWPAYMENT = '/addnewpayment';
  static const SECURITYPAGE = '/securitypage';
  static const CHANGEPASSWORD = '/changepassword';
  static const OTPSCREEN = '/otpscreen';
  static const RESETPASSWORD = '/resetpassword';
  static const DELETEACCOUNT = '/deleteaccount';
  static const PERSONALINFORMATION = '/personalinformation';
  static const PRIVACYPOLICY = '/privacypolicy';
  static const SUPPORTANDHELP = '/supportandhelp';
  static const BOOKINGDETAILS = '/bookingdetails';
  static const ENTERBOOKINGINFORMATION = '/enterbookinginformation';
  static const CITIES_ACTVITIES = '/cities-actvities';
  static const SEARCHPAGE = '/searchpage';
  static const CARTDETAILS = '/cartdetails';
  static const SPLASHSSS = '/splashsss';
  static const EDITBOOKINGS = '/editbookings';
}
